### ISSUE TITLE
kubectl plugin

### ISSUE THREAD

**Issue by ryane** [ryane/kfilt#14]
Figure out what it will take to run kfilt as a kubectl plugin

* docs
* installation instructions
* usage examples
* etc.

This can be split into multiple issues if necessary.

**Comment by djmcgreal-cc** [comment]
If you could add zipped or tar+gziped release assets, something like the following:

```yaml
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kfilt
spec:
  version: v0.0.8
  homepage: https://github.com/ryane/kfilt
  shortDescription: &description kfilt can filter Kubernetes resources
  description: *description
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
    uri: https://github.com/ryane/kfilt/releases/download/v0.0.8/kfilt_0.0.8_darwin_all.zip
    sha256: #...
    bin: kfilt_0.0.8_darwin_all
  - selector: {} #...
```

https://krew.sigs.k8s.io/docs/developer-guide/plugin-manifest
